_bootstrapGetAsset = function (path) {
  return Assets.getText(path);
};

_bootstrapGetJsList = function () {
  return jsAssetNames.slice();
}

// Do not edit this list, it is generated by the bash script, run the script instead
var jsAssetNames = ['alert.js','button.js','carousel.js','collapse.js','dropdown.js','modal.js','popover.js','scrollspy.js','tab.js','tooltip.js','util.js'];
